version: '3.9'
services:
  db:
    container_name: PostgreSQL
    image: postgres
    mem_limit: 256m
    cpu_shares: 768
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "telecom_db",
          "-U",
          "sihuan"
        ]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file: ./.env
    volumes:
      - /volume1/Docker/postgres/postgresql:/var/lib/postgresql/data:rw
    ports:
      - 2665:5432
    restart: on-failure:5

  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4:latest
    mem_limit: 256m
    cpu_shares: 768
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 2660:5050
    volumes:
      - /volume1/Docker/postgres/postgresadmin:/var/lib/pgadmin:rw
    restart: on-failure:5
