---
services:
  xtelecom:
    container_name: xtelecom
    image: sihuannewrise/xtelecom:latest
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - static:/app/static/
      - media:/app/media/
    env_file: stack.env
    networks:
      - traefik

volumes:
  static:
  media:

networks:
  traefik:
    external: true
