version: '3.8'
services:
  nocodb:
    container_name: nocodb
    depends_on:
      postgres:
        condition: service_healthy
    env_file: stack.env
    environment:
      NC_DB: "pg://postgres:5432?u=${POSTGRES_USER}&p=${POSTGRES_PASSWORD}&d=${POSTGRES_DB}"
    image: "nocodb/nocodb:latest"
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - nc_data:/usr/app/data
    networks:
      - telecom_net

  postgres:
    container_name: postgres
    image: postgres:16.1-alpine
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    env_file: stack.env
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U \"${POSTGRES_USER}\" -d \"${POSTGRES_DB}\""
      timeout: 2s
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - telecom_net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.1
    env_file: stack.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - telecom_net

  # telecom:
  #   container_name: telecom
  #   image: sihuannewrise/xtelecom:latest
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - static_value:/app/static/
  #     - media_value:/app/media/
  #   env_file: stack.env
  #   networks:
  #     - telecom_net

  nginx:
    container_name: nginx
    image: nginx:stable-alpine3.17-slim
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /volume4/dockume/app/xtelecom/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    # depends_on:
    #   - telecom
    networks:
      - telecom_net

volumes:
  nc_data:
    name: nc_data
    driver: local
    driver_opts:
      type: none
      device: /volume4/dockume/nocodb/nc_data
      o: bind

  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      device: /volume4/dockume/nocodb/db_data
      o: bind

  pgadmin_data:
    name: pgadmin_data
    driver: local
    driver_opts:
      type: none
      device: /volume4/dockume/nocodb/pgadmin_data
      o: bind

  static_value:
    name: static_value

  media_value:
    name: media_value

networks:
  telecom_net:
    name: telecom_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: $SUBNET_CIDR
