name: XTelecom-app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # service account name (any) displayed in Tuna console
  TUNA_SSH_USER: tuna_sa
  TUNA_HOST: ru.tuna.am
  # is changed every time Tuna starts (later should be constant)
  TUNA_SSH_PORT: 18148
  XTELECOM_CONTAINER_NAME: telecom
  # hostname, displayed in container conlose
  XTELECOM_HOST_NAME: telecom
  XTELECOM_NETWORK_NAME: telecom_net
  XTELECOM_SUBNET_CIDR: 172.16.1.0/24
  # manual program version indication - to be automated
  XTELECOM_VERSION: dev.1.0.6

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - 
      name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - 
      name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return
        pip install -r requirements.txt 
    - 
      name: Test with flake8 and run tests
      run: |
        python -m flake8

  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v4
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Docker 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/xtelecom:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/xtelecom:${{ env.XTELECOM_VERSION }}

  # deploy:
  #   name: Deploy on Asustor with Tuna
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: executing remote ssh commands using password
  #       uses: appleboy/ssh-action@v1.0.0
  #       with:
  #         host: ${{ env.TUNA_HOST }}
  #         username: ${{ env.TUNA_SSH_USER }}
  #         password: ${{ secrets.TUNA_SSH_PWD }}
  #         port: ${{ env.TUNA_SSH_PORT }}
  #         script: |
  #           docker stop ${{ env.XTELECOM_CONTAINER_NAME }}
  #           docker rm ${{ env.XTELECOM_CONTAINER_NAME }}
  #           docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/xtelecom:latest
  #           docker pull ${{ secrets.DOCKERHUB_USERNAME }}/xtelecom:latest
  #           docker network create \
  #             --driver=bridge \
  #             --subnet: ${{ env.XTELECOM_SUBNET_CIDR }} \
  #             ${{ env.XTELECOM_NETWORK_NAME }}
  #           docker run -d \
  #             --name=${{ env.XTELECOM_CONTAINER_NAME }} \
  #             --hostname=${{ env.XTELECOM_HOST_NAME }} \
  #             --net=${{ env.XTELECOM_NETWORK_NAME }} \
  #             --restart=unless-stopped \
  #             -v static_value:/app/static/ \
  #             -v media_value:/app/media/ \
  #             ${{ secrets.DOCKERHUB_USERNAME }}/xtelecom:latest

  inform:
    name: Send message to Telegram account
    runs-on: ubuntu-latest
    # needs: deploy
    needs: build
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Hey there!
            Рабочий поток ${{ github.workflow }} успешно выполнен!
            Репозиторий: ${{ github.repository }}
            Sincerely yours, ✨ Xwick Bot ✨
